'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OuijaBox.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Genesis 1:1	In the beginning God created the heaven and the earth.
        '''Genesis 1:2	And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.
        '''Genesis 1:3	And God said, Let there be light: and there was light.
        '''Genesis 1:4	And God saw the light, that it was good: and God divided the light from the darkness.
        '''Genesis 1:5	And God called the light Day, and the darkness he called Night. And the evening and the morning were the firs [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property bible() As String
            Get
                Return ResourceManager.GetString("bible", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to a
        '''a-horizon
        '''a-ok
        '''aardvark
        '''aardwolf
        '''ab
        '''aba
        '''abaca
        '''abacist
        '''aback
        '''abactinal
        '''abacus
        '''abaddon
        '''abaft
        '''abalienate
        '''abalienation
        '''abalone
        '''abampere
        '''abandon
        '''abandoned
        '''abandonment
        '''abarticulation
        '''abase
        '''abased
        '''abasement
        '''abash
        '''abashed
        '''abashment
        '''abasia
        '''abasic
        '''abate
        '''abatement
        '''abating
        '''abatis
        '''abatjour
        '''abattis
        '''abattoir
        '''abaxial
        '''abba
        '''abbacy
        '''abbatial
        '''abbatical
        '''abbatis
        '''abbe
        '''abbess
        '''abbey
        '''abbot
        '''abbreviate
        '''abbreviated
        '''abbreviation
        '''abbreviature
        '''abc
        '''abcoulomb
        '''abdal
        '''abderite
        '''abdicable
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property wordlist() As String
            Get
                Return ResourceManager.GetString("wordlist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AARDVARK
        '''AARDWOLF
        '''AARON
        '''ABACK
        '''ABACUS
        '''ABAFT
        '''ABALONE
        '''ABANDON
        '''ABANDONED
        '''ABANDONMENT
        '''ABANDONS
        '''ABASE
        '''ABASED
        '''ABASEMENT
        '''ABASH
        '''ABASHED
        '''ABATE
        '''ABATED
        '''ABATEMENT
        '''ABATES
        '''ABATTOIR
        '''ABATTOIRS
        '''ABBE
        '''ABBESS
        '''ABBEY
        '''ABBEYS
        '''ABBOT
        '''ABBOTS
        '''ABBREVIATE
        '''ABBREVIATED
        '''ABBREVIATES
        '''ABBREVIATING
        '''ABBREVIATION
        '''ABBREVIATIONS
        '''ABDICATE
        '''ABDICATED
        '''ABDICATES
        '''ABDICATING
        '''ABDICATION
        '''ABDOMEN
        '''ABDOMENS
        '''ABDOMINAL
        '''ABDUCT
        '''ABDUCTED
        '''ABDUCTING
        '''ABDUCTION
        '''ABDUCTIONS
        '''ABDUCTOR
        '''ABDUCTORS
        '''ABDUCTS
        '''ABE
        '''ABEAM
        '''ABEL
        '''ABE [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property wordlistcaps() As String
            Get
                Return ResourceManager.GetString("wordlistcaps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to aardvark
        '''aardwolf
        '''aaron
        '''aback
        '''abacus
        '''abaft
        '''abalone
        '''abandon
        '''abandoned
        '''abandonment
        '''abandons
        '''abase
        '''abased
        '''abasement
        '''abash
        '''abashed
        '''abate
        '''abated
        '''abatement
        '''abates
        '''abattoir
        '''abattoirs
        '''abbe
        '''abbess
        '''abbey
        '''abbeys
        '''abbot
        '''abbots
        '''abbreviate
        '''abbreviated
        '''abbreviates
        '''abbreviating
        '''abbreviation
        '''abbreviations
        '''abdicate
        '''abdicated
        '''abdicates
        '''abdicating
        '''abdication
        '''abdomen
        '''abdomens
        '''abdominal
        '''abduct
        '''abducted
        '''abducting
        '''abduction
        '''abductions
        '''abductor
        '''abductors
        '''abducts
        '''abe
        '''abeam
        '''abel
        '''abe [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property wordlistlowercase() As String
            Get
                Return ResourceManager.GetString("wordlistlowercase", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
